M48
; DRILL file {KiCad (7.0.0)} date Wed Mar 22 16:08:02 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-22T16:08:02+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
%
G90
G05
T1
X3.7874Y-3.0827
X3.7874Y-3.9882
X4.6929Y-3.0827
X4.6929Y-3.9882
T0
M30
